### ISSUE TITLE
Markdown Linting

### ISSUE THREAD

**Issue by VoyTechnology** [SaferPlace/saferplace#173]
If a file is a markdown file, we should lint it for style or maybe some obvious typos.

**Comment by yo-404** [comment]
I tried running running language tool and misspell check on markdown files . Added a CI action file spellcheck.yml . 
Here's the result - https://github.com/yo-404/saferplace/actions/runs/6121405779

![image](https://github.com/SaferPlace/saferplace/assets/100558220/6a2a63c6-2a1f-4dac-95f5-c4390774fd94)

**Comment by VoyTechnology** [comment]
Hey @yo-404, thank you for looking into this! Do you mind sending in a PR for your change? We can merge it and then look into fixing all of the issues that you have found.

**Comment by yo-404** [comment]
Sure @VoyTechnology . Have sent a PR regarding the same . Spellcheck action has been set to run on each `commit` which can be changed to `pr-check` as per requirements .
